use builtin translate-c
since 0.16, translate-c is built into zig. this commit gets rid of the
external dep and uses the builtin one

this also fixes issues on non fhs standard systems like nixos where it
would fail with errors like

> fatal error: 'stdio.h' not found